services:
  - type: web
    name: easymeet-backend
    runtime: node
    rootDir: Backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        sync: false

  - type: static
    name: easymeet-frontend
    rootDir: Frontend
    buildCommand: npm install && npm run build
    publishDir: build
    envVars:
      - key: REACT_APP_API_URL
        value: https://easymeet-backend.onrender.com/api/v1/users
      - key: REACT_APP_SOCKET_URL
        value: https://easymeet-backend.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
